### ISSUE TITLE
[dev/flutter2] Local view in Web does not start mirrored

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Agora-Flutter-SDK#420]
In iOS and Android when the local preview starts, by default it is a mirrored view that is natural for the user. The web version starts without mirroring of the image. 

Please align web with the mobile platforms behaviour.

**Comment by NSFriend** [comment]
Have same issue

**Comment by reeteshranjan** [comment]
I have tried this solution for now. Yet to test any performance issues.

```dart
Transform(
  transform: Matrix4.rotationY(pi),
  alignment: Alignment.center,
  child: widget,
)
```

The child widget is either remote or local view.

**Comment by LichKing-2234** [comment]
Fixed

**Comment by rgb1380** [comment]
@LichKing-2234 Just checked and the changes have not fixed the issue.

**Comment by LichKing-2234** [comment]
@rgb1380 Not support auto on the Web platform now, I have the plan to implement it.

**Comment by rgb1380** [comment]
Fixed. Thanks!

**Comment by rgb1380** [comment]
@LichKing-2234 the update has broken screen sharing. RtcLocalView.SurfaceView.screenShare() now displays the local video.
The new AgoraRtcWrapper.bundle.js is only 688kb compared to the previous one which was 806kb. When I use the old one, screen sharing works for me.

**Comment by LichKing-2234** [comment]
@rgb1380 Fixed.
