### ISSUE TITLE
Could not find native-full-sdk-3.5.2.jar

### ISSUE THREAD

**Issue by stevanusw28** [AgoraIO/Agora-Flutter-SDK#650]
**Describe the bug**
The app can't be built because there is error when building from agora finding native-full-sdk-3.5.2.jar.
Is there any error in the dependencies jitpack.io ?
```
FAILURE: Build completed with 14 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:androidDependencies'.
> Could not resolve all artifacts for configuration ':app:devGrowthCompileClasspath'.
   > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2).
     Searched in the following locations:
         https://jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':feature_category:androidDependencies'.
> Could not resolve all artifacts for configuration ':feature_category:devGrowthCompileClasspath'.
   > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2).
     Searched in the following locations:
         https://jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

**To Reproduce**
Run the application using agora library sdk

**Expected behavior**
The app can be successfully build and run

**Smartphone (please complete the following information):**
 - Device: Samsung A52
 - OS: One UI
 - Version: Android 12

**Comment by badgeek** [comment]
cross reference to https://github.com/AgoraIO-Community/react-native-agora/issues/486

**Comment by dhimanrascon** [comment]
Same issue for me.

Running Gradle task 'assembleDevRelease'...                     

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileReleaseKotlin'.
> Could not resolve all files for configuration ':agora_rtc_engine:***CompileClasspath'.
   > Failed to transform native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=***, org.gradle.usage=java-api}.
      > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2).
        Searched in the following locations:
            https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 58s
Running Gradle task 'assembleDevRelease'...                       [35](https://github.com/asconsoft/gintaa-app/runs/6001138840?check_suite_focus=true#step:9:35)9.6s

**Comment by littleGnAl** [comment]
There's an issue that jitpack.io lost the dependency sometimes, we had published the dependency to maven center, you can try to change the implementation from `implementation 'com.github.agorabuilder:native-full-sdk:3.5.2'` to `implementation 'io.agora.rtc:full-sdk:3.5.2' ` at this time.

**Comment by congddl** [comment]
I have same the issues . It just arrived today and i can`t build an apk android in Bitrise

**Comment by littleGnAl** [comment]
In `agora_rtc_engine: 5.1.0`, we don't depend on the native SDK directly, you can fork and change the dependency, then reference it as a [git package](https://dart.dev/tools/pub/dependencies#git-packages) temporarily at this time.

**Comment by abhisheka-asconsoft** [comment]
> In `agora_rtc_engine: 5.1.0`, we don't depend on the native SDK directly, you can fork and change the dependency, then reference it as a [git package](https://dart.dev/tools/pub/dependencies#git-packages) temporarily at this time.

@littleGnAl Thank you for the temporary solution. Do we have a time frame for when any official solution will be available for this?

**Comment by littleGnAl** [comment]
Hello guys
We had published the `agora_rtc_engine: 4.2.2` based on the `agora_rtc_engine: 4.2.1`, but only change the dependency, this issue should be fixed now.
https://pub.dev/packages/agora_rtc_engine/versions/4.2.2

**Comment by dhimanrascon** [comment]
Fixed for me now. Thanks @littleGnAl

**Comment by TetsuFe** [comment]
Thanks @littleGnAl
But why not 5.0.2?

**Comment by luongdong059** [comment]
Same issue for me

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileReleaseKotlin'.
> Could not resolve all artifacts for configuration ':agora_rtc_engine:releaseCompileClasspath'.
   > Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.4.6/native-full-sdk-3.4.6.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by littleGnAl** [comment]
@luongdong059 Can you try `agora_rtc_engine: 4.2.2` or the latest version?

**Comment by MarianoAmado** [comment]
@littleGnAl
I'm having this same issue with `agora_rtc_engine: 3.4.6` in a flutter 1 based project

```
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6).
     Searched in the following locations:
         https://jitpack.io/com/github/agorabuilder/native-full-sdk/3.4.6/native-full-sdk-3.4.6.jar
```

Could you guys please publish that fix for the non null-safety version?

**Comment by wsb1689** [comment]
@luongdong059 have you solved this question at versions 3.4.6

**Comment by atleugim** [comment]
> @luongdong059 have you solved this question at versions 3.4.6

This is still happening to me on a Flutter 1.22.6 project with v3.3.3 agora plugin

**Comment by Prowtonz** [comment]
Has anyone been able to find a solution? I'm also getting the `Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6)` error.

**Comment by imrandesign** [comment]
yes solved by this 
implementation 'com.github.agorabuilder:native-full-sdk:3.5.2' replace  implementation 'io.agora.rtc:full-sdk:3.5.2'

**Comment by socialmad** [comment]
* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
> Could not resolve all files for configuration ':agora_rtc_engine:debugCompileClasspath'.
   > Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.4.6/native-full-sdk-3.4.6.jar


I am also facing the same issue, my project is running on Flutter 1.22.0.
Can anyone please help?

**Comment by qamaruddin-dev** [comment]
For anyone who is still facing this issue

1: Run flutter pub outdated --mode=null-safety to check which dependencies are outdated

2: Run flutter pub upgrade --null-safety to upgrade all dependencies

3: It would update agora_rtc_engine to latest sdk, try to change that to agora_rtc_engine: 4.2.2

4: Set ext.kotlin_version = '1.6.10' in *build.gradle

Note: If you face any incompatibility with other packages for setting minSdk as 19, change minSdk to 19

5: If you faced any gradle error, you might need to change gradle-wrapper.properties

//add this line distributionUrl=https://services.gradle.org/distributions/gradle-7.3.1-all.zip

Thats all
